[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sonar"
path = "src/sonar.rs"

[[bin]]
name = "dive"
path = "src/dive.rs"

[[bin]]
name = "binary-diagnostic"
path = "src/binary-diagnostic.rs"

[[bin]]
name = "bingo"
path = "src/bingo.rs"

[[bin]]
name = "vents"
path = "src/vents.rs"

[[bin]]
name = "lanternfish"
path = "src/lanternfish.rs"


[dependencies]
